spring:
  data:
    mongodb:
      database: project01
      host: localhost
      port: 27017
      
server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'